name: raffle_time
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  url_launcher: ^6.1.10
  walletconnect_dart: ^0.0.11
  web3dart: ^2.6.1
  http: ^0.13.5
  intl: ^0.18.0
  flutter_datetime_picker: ^1.5.1
  walletconnect_secure_storage: ^1.0.0
  share_plus: ^6.3.2
  hex: ^0.2.0

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/abi/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf


